import type { CommunityItem } from '@/types';

export const COMMUNITY_PRIMARY_TABS = ['Trending', 'Following', 'Saved', 'Templates', 'Creators'] as const;
export const COMMUNITY_FILTER_CHIPS = ['Recent', 'Popular', 'Dreamy', 'Lifestyle', 'Product', 'Experimental', 'Horror', 'Fashion'] as const;

export const COMMUNITY_INSPIRATIONS: CommunityItem[] = [
  {
    id: 'sea_garden_perfume',
    title: 'A Dive into the Senses | Sea Garden',
    creator: 'C-AIGC',
    handle: '@c_aigc',
    creatorAvatar: '',
    likes: 42,
    duration: '00:15',
    description: 'A perfume-led underwater composition with soft bloom, glass highlights, and a calm cinematic cadence.',
    category: 'Product',
    image: '/assets/story-2.jpg',
    mediaUrl: '/assets/demo-video.mp4',
    type: 'video',
    date: '2026-03-26',
    tags: ['Product', 'Dreamy', 'Premium'],
    badges: ['Featured', 'Mock'],
    whyItWorks: 'The reference uses a limited material palette and soft underwater pacing, so every cut feels tactile and premium without losing clarity.',
    bestUsedFor: ['Luxury fragrance films', 'Premium product launches', 'Soft-focus brand openers'],
  },
  {
    id: 'city_rain_reflections',
    title: 'City Rain Reflections',
    creator: 'Nightframe Studio',
    handle: '@nightframe',
    creatorAvatar: '',
    likes: 318,
    duration: '00:18',
    description: 'A rain-soaked city piece built on window reflections, headlights, and slow tracking movement.',
    category: 'Lifestyle',
    image: '/assets/trending-3.jpg',
    type: 'image',
    date: '2026-04-02',
    tags: ['Lifestyle', 'Recent', 'Moody'],
    badges: ['Recent', 'Mock'],
    whyItWorks: 'Rain reflections add density and depth, so the frame feels rich even with simple camera movement.',
    bestUsedFor: ['Night city reels', 'Moody lifestyle edits', 'Travel intros'],
  },
  {
    id: 'forest_dream_passage',
    title: 'Forest Dream Passage',
    creator: 'Luma Archive',
    handle: '@luma_archive',
    creatorAvatar: '',
    likes: 267,
    duration: '00:14',
    description: 'A low-contrast forest dream that moves through haze, slow pans, and soft green atmosphere.',
    category: 'Dreamy',
    image: '/assets/trending-1.jpg',
    type: 'image',
    date: '2026-03-29',
    tags: ['Dreamy', 'Popular', 'Nature'],
    badges: ['Popular'],
    whyItWorks: 'The imagery stays emotionally legible because it limits contrast and keeps motion slow and coherent.',
    bestUsedFor: ['Mood films', 'Nature references', 'Soft emotional transitions'],
  },
  {
    id: 'backrooms_signal',
    title: 'Backrooms Signal',
    creator: 'Analog Haze',
    handle: '@analog_haze',
    creatorAvatar: '',
    likes: 512,
    duration: '00:15',
    description: 'A fluorescent found-footage corridor with handheld tension, repeating geometry, and one final glitch.',
    category: 'Horror',
    image: '/mock/backrooms/分镜 03.png',
    mediaUrl: '/mock/backrooms/demo video.mp4',
    type: 'video',
    date: '2026-04-08',
    tags: ['Horror', 'Experimental', 'Liminal'],
    badges: ['Featured'],
    whyItWorks: 'The repeating spatial language creates dread fast, and the final glitch gives the piece a clean unresolved ending.',
    bestUsedFor: ['Suspense scripts', 'Liminal references', 'POV horror beats'],
  },
  {
    id: 'fashion_street_afterglow',
    title: 'Fashion Street Afterglow',
    creator: 'Atelier Motion',
    handle: '@atelier_motion',
    creatorAvatar: '',
    likes: 226,
    duration: '00:21',
    description: 'An airy fashion sequence with reflective storefronts, fabric motion, and editorial pacing.',
    category: 'Fashion',
    image: '/assets/trending-7.jpg',
    type: 'image',
    date: '2026-04-11',
    tags: ['Fashion', 'Popular', 'Editorial'],
    badges: ['Popular'],
    whyItWorks: 'The edit alternates between silhouette and detail, which keeps the look aspirational without becoming static.',
    bestUsedFor: ['Fashion reels', 'Brand moodboards', 'Editorial concepting'],
  },
  {
    id: 'cafe_night_memory',
    title: 'Cafe Night Memory',
    creator: 'After Hours Lab',
    handle: '@afterhours_lab',
    creatorAvatar: '',
    likes: 188,
    duration: '00:20',
    description: 'An intimate rainy-night cafe composition shaped by tungsten glow, glass reflections, and unresolved emotion.',
    category: 'Lifestyle',
    image: '/assets/trending-5.jpg',
    type: 'image',
    date: '2026-03-30',
    tags: ['Lifestyle', 'Dreamy', 'Narrative'],
    badges: ['Mock'],
    whyItWorks: 'The piece feels cinematic because it stays restrained and lets reflections and body language carry the emotion.',
    bestUsedFor: ['Narrative vignettes', 'Cafe mood references', 'Bittersweet short films'],
  },
  {
    id: 'cyberpunk_alley_pulse',
    title: 'Cyberpunk Alley Pulse',
    creator: 'Vector K',
    handle: '@vector_k',
    creatorAvatar: '',
    likes: 441,
    duration: '00:17',
    description: 'A neon alley reference driven by wet pavement, fast perspective shifts, and electric edge lighting.',
    category: 'Experimental',
    image: '/assets/trending-4.jpg',
    type: 'video',
    mediaUrl: '/assets/demo-video.mp4',
    date: '2026-04-05',
    tags: ['Experimental', 'Popular', 'Neon'],
    badges: ['Recent'],
    whyItWorks: 'The contrast between dark alleys and neon edges creates instant visual rhythm and makes speed legible.',
    bestUsedFor: ['Action teasers', 'Cyberpunk moodboards', 'Tech launch visuals'],
  },
  {
    id: 'bedroom_routine_softlight',
    title: 'Bedroom Routine Softlight',
    creator: 'Soft Daily',
    handle: '@softdaily',
    creatorAvatar: '',
    likes: 163,
    duration: '00:12',
    description: 'A morning routine reference built on natural light, linen texture, and gentle domestic pacing.',
    category: 'Lifestyle',
    image: '/assets/citywalk/morning.png',
    type: 'image',
    date: '2026-04-01',
    tags: ['Lifestyle', 'Recent', 'Warm'],
    badges: ['Recent'],
    whyItWorks: 'The rhythm stays soothing because every beat is a familiar action framed with the same calm light language.',
    bestUsedFor: ['Routine films', 'Home lifestyle edits', 'Soft daily inspiration'],
  },
  {
    id: 'abstract_motion_study',
    title: 'Abstract Motion Study',
    creator: 'Shape Fiction',
    handle: '@shapefiction',
    creatorAvatar: '',
    likes: 207,
    duration: '00:10',
    description: 'A gradient-led abstract motion reference mixing light leaks, soft particles, and shape transitions.',
    category: 'Experimental',
    image: '/assets/trending-6.jpg',
    type: 'video',
    mediaUrl: '/assets/demo-video.mp4',
    date: '2026-03-24',
    tags: ['Experimental', 'Dreamy', 'Motion'],
    badges: ['Mock'],
    whyItWorks: 'Abstract transitions become reusable because the motion language stays clean and repeats with intent.',
    bestUsedFor: ['Transitions', 'Title sequences', 'Mood interstitials'],
  },
  {
    id: 'food_commercial_glow',
    title: 'Food Commercial Glow',
    creator: 'Tasteframe',
    handle: '@tasteframe',
    creatorAvatar: '',
    likes: 129,
    duration: '00:16',
    description: 'A fast premium food commercial built on steam, glossy highlights, and satisfying macro cuts.',
    category: 'Product',
    image: '/assets/story-4.jpg',
    type: 'image',
    date: '2026-04-09',
    tags: ['Product', 'Popular', 'Commercial'],
    badges: ['Featured'],
    whyItWorks: 'Macro inserts and steam cues instantly signal freshness and production value without needing complex staging.',
    bestUsedFor: ['Food ads', 'Menu promos', 'High-texture product spots'],
  },
  {
    id: 'travel_vlog_riverside',
    title: 'Travel Vlog Riverside',
    creator: 'Roam Memory',
    handle: '@roammemory',
    creatorAvatar: '',
    likes: 284,
    duration: '00:19',
    description: 'A travel opener that alternates landscape scale with handheld human moments along a riverside route.',
    category: 'Lifestyle',
    image: '/assets/citywalk/landmark.png',
    type: 'video',
    mediaUrl: '/assets/demo-video.mp4',
    date: '2026-03-21',
    tags: ['Lifestyle', 'Popular', 'Travel'],
    badges: ['Popular'],
    whyItWorks: 'The sequence balances place identity and personal immediacy, so it works both as travel and as creator content.',
    bestUsedFor: ['Travel intros', 'Lifestyle vlogs', 'Destination teasers'],
  },
  {
    id: 'surreal_ocean_bloom',
    title: 'Surreal Ocean Bloom',
    creator: 'Pelagic Dreams',
    handle: '@pelagicdreams',
    creatorAvatar: '',
    likes: 356,
    duration: '00:15',
    description: 'A surreal ocean composition with floating particles, soft coral forms, and a suspended premium mood.',
    category: 'Dreamy',
    image: '/assets/story-1.jpg',
    type: 'image',
    date: '2026-04-03',
    tags: ['Dreamy', 'Product', 'Premium'],
    badges: ['Featured', 'Mock'],
    whyItWorks: 'The underwater palette is calm but visually rich, making it flexible for sensory branding and poetic visuals.',
    bestUsedFor: ['Beauty references', 'Oceanic mood films', 'Premium campaign decks'],
  },
  {
    id: 'retro_interior_loop',
    title: 'Retro Interior Loop',
    creator: 'Loop Bureau',
    handle: '@loopbureau',
    creatorAvatar: '',
    likes: 246,
    duration: '00:13',
    description: 'A retro-styled interior study with warm lamps, wood grain, and a looping analog calm.',
    category: 'Dreamy',
    image: '/assets/story-3.jpg',
    type: 'image',
    date: '2026-04-12',
    tags: ['Dreamy', 'Recent', 'Interior'],
    badges: ['Recent', 'Mock'],
    whyItWorks: 'The nostalgic palette and controlled loop length make it easy to reference for interiors without overcomplicating the frame.',
    bestUsedFor: ['Interior moodboards', 'Memory sequences', 'Warm retro edits'],
  },
  {
    id: 'office_liminal_shift',
    title: 'Office Liminal Shift',
    creator: 'Spatial Null',
    handle: '@spatialnull',
    creatorAvatar: '',
    likes: 291,
    duration: '00:16',
    description: 'An empty office corridor study where fluorescent repetition slowly drifts into liminal discomfort.',
    category: 'Horror',
    image: '/assets/backrooms-1.jpg',
    type: 'image',
    date: '2026-04-10',
    tags: ['Horror', 'Recent', 'Liminal'],
    badges: ['Recent'],
    whyItWorks: 'It captures workplace familiarity before the spatial drift starts, which makes the unease arrive faster.',
    bestUsedFor: ['Office suspense', 'Liminal horror references', 'Found-space tension'],
  },
  {
    id: 'glass_product_macro',
    title: 'Glass Product Macro',
    creator: 'Specular Lab',
    handle: '@specularlab',
    creatorAvatar: '',
    likes: 204,
    duration: '00:11',
    description: 'A macro product reference focused on glass edges, liquid refraction, and controlled premium highlights.',
    category: 'Product',
    image: '/assets/fragrance/closeup.png',
    type: 'image',
    date: '2026-04-04',
    tags: ['Product', 'Premium', 'Macro'],
    badges: ['Featured'],
    whyItWorks: 'The macro framing makes the object feel expensive while still leaving room for brand overlays and copy.',
    bestUsedFor: ['Luxury product ads', 'Bottle hero shots', 'Macro references'],
  },
  {
    id: 'street_dance_cut',
    title: 'Street Dance Cut',
    creator: 'Pulse Method',
    handle: '@pulsemethod',
    creatorAvatar: '',
    likes: 377,
    duration: '00:18',
    description: 'A fast-cut street dance piece that mixes pavement texture, body rhythm, and urban daylight energy.',
    category: 'Fashion',
    image: '/assets/citywalk/shopping.png',
    type: 'video',
    mediaUrl: '/assets/demo-video.mp4',
    date: '2026-04-06',
    tags: ['Fashion', 'Popular', 'Movement'],
    badges: ['Popular'],
    whyItWorks: 'The body movement creates a ready-made edit rhythm, so even simple environments feel dynamic.',
    bestUsedFor: ['Dance edits', 'Movement studies', 'Streetwear reels'],
  },
  {
    id: 'mountain_morning_breath',
    title: 'Mountain Morning Breath',
    creator: 'North Still',
    handle: '@northstill',
    creatorAvatar: '',
    likes: 192,
    duration: '00:17',
    description: 'A mountain morning reference with crisp air, long shadows, and a slow opening reveal over ridgelines.',
    category: 'Lifestyle',
    image: '/assets/trending-1.jpg',
    type: 'image',
    date: '2026-04-07',
    tags: ['Lifestyle', 'Recent', 'Travel'],
    badges: ['Recent'],
    whyItWorks: 'It feels cinematic because scale and stillness are doing most of the work, leaving the edit clean and spacious.',
    bestUsedFor: ['Travel openers', 'Outdoor mood films', 'Morning atmosphere'],
  },
  {
    id: 'rain_window_mood',
    title: 'Rain Window Mood',
    creator: 'Soft Static',
    handle: '@softstatic',
    creatorAvatar: '',
    likes: 231,
    duration: '00:09',
    description: 'A minimal rain-on-glass reference focused on shallow depth, soft practicals, and a single emotional beat.',
    category: 'Dreamy',
    image: '/assets/story-4.jpg',
    type: 'image',
    date: '2026-04-13',
    tags: ['Dreamy', 'Recent', 'Mood'],
    badges: ['Recent', 'Featured'],
    whyItWorks: 'Because the frame stays minimal, it becomes a highly reusable emotional insert rather than a locked narrative scene.',
    bestUsedFor: ['Mood inserts', 'Rain motifs', 'Quiet narrative beats'],
  },
  {
    id: 'luxury_bag_ad',
    title: 'Luxury Bag Ad',
    creator: 'Maison Render',
    handle: '@maisonrender',
    creatorAvatar: '',
    likes: 348,
    duration: '00:14',
    description: 'A high-end accessory commercial reference using slow rotation, leather texture, and polished spotlight falloff.',
    category: 'Product',
    image: '/assets/trending-7.jpg',
    type: 'video',
    mediaUrl: '/assets/demo-video.mp4',
    date: '2026-04-14',
    tags: ['Product', 'Fashion', 'Premium'],
    badges: ['Featured', 'Popular'],
    whyItWorks: 'It isolates the product with enough motion to feel premium while staying simple enough to reuse across campaigns.',
    bestUsedFor: ['Accessory launches', 'Luxury reels', 'Product hero references'],
  },
  {
    id: 'memory_corridor',
    title: 'Memory Corridor',
    creator: 'Archive Echo',
    handle: '@archiveecho',
    creatorAvatar: '',
    likes: 258,
    duration: '00:12',
    description: 'A corridor memory piece built on soft haze, distant glow, and the feeling of almost-recognized space.',
    category: 'Dreamy',
    image: '/assets/trending-7.jpg',
    type: 'image',
    date: '2026-04-15',
    tags: ['Dreamy', 'Popular', 'Interior'],
    badges: ['Recent'],
    whyItWorks: 'The reference is abstract enough to stay flexible but still spatially clear enough to guide scene composition.',
    bestUsedFor: ['Memory motifs', 'Dream corridors', 'Interior transitions'],
  },
];

export const HOME_TRENDING_TABS = ['All', ...COMMUNITY_FILTER_CHIPS] as const;
